### ISSUE TITLE
Adding a .desktop as a asset?

### ISSUE THREAD

**Issue by SolarAquarion** [bleenco/bterm#118]

**Comment by marhi** [comment]
Please provide a description otherwise the issue will be closed due to lack of information. Thank you.

**Comment by SolarAquarion** [comment]
A .desktop is a thing that is installed on Linux systems under
/usr/share/applications and is meant to populate menus

**Comment by SolarAquarion** [comment]
I found that the app makes a deb, i just unpacked that and cp'd usr/share
