### ISSUE TITLE
[bug] I'm getting black screen when launching bterm

### ISSUE THREAD

**Issue by SolarAquarion** [bleenco/bterm#121]
When i launch bterm i'm getting a black screen with no details shown

**Comment by jkuri** [comment]
does that happen when running production build or dev build? try opening chrome devtools and see what console says.

**Comment by SolarAquarion** [comment]
Production builds

**Comment by SolarAquarion** [comment]
I can't access chrome devtools

**Comment by jkuri** [comment]
use keyboard shortcuts, cmd+shift+i if you are on mac.

**Comment by SolarAquarion** [comment]
I'm on linux

**Comment by SolarAquarion** [comment]
@jkuri I have the devtools open
![screenshot from 2017-07-24 13 52 01](https://user-images.githubusercontent.com/5307016/28536975-56c668b8-7077-11e7-90ef-f5154c58a4ab.png)

**Comment by jkuri** [comment]
check the console, there's one error.

**Comment by jkuri** [comment]
I tried running on Linux and it works.
```sh
sudo apt-get install libfontconfig-dev -y # this is important
git clone https://github.com/bleenco/bterm.git
cd bterm
npm install
npm run app:linux
```
let me know if it works for you.

**Comment by SolarAquarion** [comment]
Uncaught Error: The module '/tmp/.org.chromium.Chromium.ZMQfvL'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/bterm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:21:11)
    at Object.<anonymous> (/usr/lib/bterm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:227:3)

**Comment by SolarAquarion** [comment]
Which file has the .desktop because it does package a .deb

**Comment by jkuri** [comment]
check the `dist/` folder. if you want something else than `.deb`, check [this](https://github.com/electron-userland/electron-packager) out.

**Comment by SolarAquarion** [comment]
the deb is okay.  It's just a matter of moving stuff around

**Comment by SolarAquarion** [comment]
But the the node module

**Comment by SolarAquarion** [comment]
@jkuri tried electron-rebuild and it failed

**Comment by jkuri** [comment]
@SolarAquarion try now. I updated `npm run build:prod` command.

**Comment by SolarAquarion** [comment]
@jkuri you didn't push?

**Comment by jkuri** [comment]
you are right. i did now :P

**Comment by SolarAquarion** [comment]
@jkuri I'm now getting a issue where I can't scroll up or down in the side settings.

**Comment by jkuri** [comment]
I see, will check about the fix. thanks
