### ISSUE TITLE
I can't scroll up or down on fonts

### ISSUE THREAD

**Issue by SolarAquarion** [bleenco/bterm#124]

**Comment by SolarAquarion** [comment]
@marhi @jkuri I can't scroll up or down on themes either

**Comment by jkuri** [comment]
@SolarAquarion thanks, assigned this to myself and will do a fix till the end of week hopefully. I am suspecting `ngx-slimscroll` to be the reason for this behaviour.

**Comment by jkuri** [comment]
@SolarAquarion I made a new build for MacOS with the fix applied; https://github.com/bleenco/bterm/releases/download/v1.0.1/bterm-1.0.1.dmg. Thanks for using bterm :).

**Comment by SolarAquarion** [comment]
I use linux though.  lol

**Comment by jkuri** [comment]
here you go; https://github.com/bleenco/bterm/releases/download/v1.0.1/bterm_1.0.1_amd64.deb.zip. please let me know if it works for you.

**Comment by SolarAquarion** [comment]
works great

**Comment by irmana** [comment]
@jkuri thanks for resolving this issue!
