### ISSUE TITLE
1.0.0 does not work if ~/.bashrc file does not exist

### ISSUE THREAD

**Issue by jokeyrhyme** [bleenco/bterm#125]
Very cool project, yay!

I downloaded 1.0.0 for macOS, and upon launch I only see a black unresponsive window

The developer console revealed a thrown error, caused by me not having a ~/.bashrc file (I'm a zsh user)

I ran `touch ~/.bashrc` and now it works :)

**Comment by jkuri** [comment]
hi @jokeyrhyme! thank you for this report. working on the fix ...
