### ISSUE TITLE
npm run app doesn't build actual binaries?

### ISSUE THREAD

**Issue by SolarAquarion** [bleenco/bterm#137]

**Comment by SolarAquarion** [comment]
⚠️  Application category is not set for Linux (linux.category).
Please see https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions-category

**Comment by jkuri** [comment]
it does build actual binaries, this is just a warning that app is not categorized.

**Comment by SolarAquarion** [comment]
electron-builder 19.22.1
Installing app dependencies for arch x64 to /home/solaraquarion/pkgbuild/bterm-git/src/bterm-git/build
Packaging for linux x64 using electron 1.7.5 to dist/linux-unpacked
{ Error: Cannot find module '7zip-bin-linux'

**Comment by jkuri** [comment]
`npm install 7zip-bin-linux && sudo apt-get install graphicsmagick icnsutils -y` if you want to make build youself.

**Comment by SolarAquarion** [comment]
I have all of those installed, but the 7zip thing is a dependency

**Comment by jkuri** [comment]
please run command I posted above and it will work :) thanks
