### ISSUE TITLE
configure CircleCI for Linux & macOS

### ISSUE THREAD

**Issue by jkuri** [bleenco/bterm#16]
`CircleCI` configuration needs to be configured to automatically run tests after every PR and every merge.  We can help ourselves with [this](https://github.com/angular/angular-cli/blob/master/.travis.yml) configuration. 
This task is in schedule after https://github.com/bleenco/bterm/issues/15 is resolved.

**Comment by omerson** [comment]
This issue is close by https://github.com/bleenco/bterm/pull/23
