### ISSUE TITLE
Unable to exit fullscreen mode on Windows

### ISSUE THREAD

**Issue by omerson** [bleenco/bterm#3]
After entering fullscreen mode on the green icon in the header, I was unable to exit the full screen. Expected behaviour would be to exit the mode by clicking the same icon or pressing ESC button. This can be problematic since it covers taskbar on windows. Should it leave the taskbar open as other windows applications?

I am using windows 7 and 8,1 and bterm version 0.7.3.

**Comment by jkuri** [comment]
hi @omerson, thanks for report. will investigate on that and find a fix asap.
