### ISSUE TITLE
[bug] Clicking or drag-and-dropping link into bterm

### ISSUE THREAD

**Issue by irmana** [bleenco/bterm#82]
Reproduce: Click a link to the webpage inside of the `bterm` or drag and drop a link into the `bterm` window.

Bug: It opens up a webpage inside of the `bterm` window. 

Proposed: 
- Clicking the link should open up the link in the default browser.
- Drag-and-dropping the link should paste the text of the link into the terminal.

**Comment by shumail92** [comment]
@irmana  For the first point of proposed solution, the default mac or ubuntu terminal makes the link to any webpage un-clickable so perhaps we can stick to same behavior too?
For the second point, i am unable to reproduce it. In fact, If i drag any link or any other file, `bterm` crashes. I'll try to fix this.

**Comment by shumail92** [comment]
You can still click a link in bterm and which opens link in bterm window.
New issue for that: #91
